-- Canonical seed for the Physical Therapy dataset
-- Re-runnable on the canonical schema.

insert into faculties (name)
values ('Faculty of Physical Therapy')
on conflict (name) do nothing;

insert into programs (faculty_id, name, duration_years)
values (
  (select id from faculties where name = 'Faculty of Physical Therapy'),
  'Physical Therapy Program',
  5
)
on conflict (faculty_id, name) do nothing;

-- Physical Therapy program seed from data.js
-- Step 3: insert shared course names
insert into courses (name) values
  ('Biophysics (for Physiotherapy)'),
  ('Ethics and Laws'),
  ('Anatomy 1 (for physiotherapy)'),
  ('Histology 1 (for physiotherapy)'),
  ('Physiology 1 (for physiotherapy)'),
  ('Biochemistry (for physiotherapy)'),
  ('University Requirement (1)'),
  ('Kinesiology 1'),
  ('Tests and Measurements 1'),
  ('Anatomy 2 (for physiotherapy)'),
  ('Histology 2 (for physiotherapy)'),
  ('Physiology 2 (for physiotherapy)'),
  ('University Requirement (2)'),
  ('University Requirement (3)'),
  ('Kinesiology 2'),
  ('Tests and Measurements 2'),
  ('Growth and Development and Human Genetics'),
  ('Neuroanatomy (for physiotherapy)'),
  ('Neurophysiology 1 (for physiotherapy)'),
  ('Clinical Biochemistry (for physiotherapy)'),
  ('Biomechanics 1'),
  ('Therapeutic Modalities'),
  ('Exercise Physiology'),
  ('Anatomy 3 (for physiotherapy)'),
  ('Neurophysiology 2 (for physiotherapy)'),
  ('University Requirement (4)'),
  ('Biomechanics 2'),
  ('Pathology 1 (for physiotherapy)'),
  ('Pharmacology 1 (for physiotherapy)'),
  ('Theory of Internal Medicine (for physiotherapy)'),
  ('Cardiothoracic Surgery (for physiotherapy)'),
  ('Radiology 1 (for physiotherapy)'),
  ('Elective Course (1)'),
  ('Cardiopulmonary and Internal Medicine PT and Rehabilitation'),
  ('Pathology 2 (for physiotherapy)'),
  ('Pharmacology 2 (for physiotherapy)'),
  ('General Surgery (for physiotherapy)'),
  ('Obstetrics & Gynaecology (for physiotherapy)'),
  ('Public Health (for physiotherapy)'),
  ('Elective Course (2)'),
  ('Integumentary PT and Rehabilitation'),
  ('Woman Health PT and Rehabilitation'),
  ('Radiology 2 (for physiotherapy)'),
  ('Traumatology and Orthopaedic Surgery'),
  ('University Requirement (5)'),
  ('University Requirement (6)'),
  ('Elective University Requirement (1)'),
  ('Sport injuries PT and Rehabilitation'),
  ('Orthopaedics PT and Rehabilitation'),
  ('Paediatric Surgery (for physiotherapy)'),
  ('Paediatrics (for physiotherapy)'),
  ('Elective Course (3)'),
  ('Orthoses and Prostheses'),
  ('Paediatrics PT and Rehabilitation'),
  ('Electro-diagnosis (for physiotherapy)'),
  ('Neuropsychiatry (for physiotherapy)'),
  ('Neurosurgery (for physiotherapy)'),
  ('Radiology 3 (for physiotherapy)'),
  ('Elective Course (4)'),
  ('University Requirement (7)'),
  ('Elective University (2)'),
  ('Neurology PT and Rehabilitation'),
  ('Neurosurgery PT and Rehabilitation'),
  ('Differential Diagnosis 1 (for physiotherapy)'),
  ('Elective Course (5)'),
  ('Elective University (3)'),
  ('Graduation Research Project');
on conflict (name) do nothing;

-- Step 4: add credits if the column does not exist yet
alter table program_courses
  add column if not exists credits smallint not null default 0;

-- Step 4 continued: insert program-specific course rows
insert into program_courses
(program_id, course_id, code, year_no, semester_no, credits, is_required)
values
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Biophysics (for Physiotherapy)'),
   'PHY112', 1, 1, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Ethics and Laws'),
   'BPT111', 1, 1, 1, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Anatomy 1 (for physiotherapy)'),
   'BMS115', 1, 1, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Histology 1 (for physiotherapy)'),
   'BMS124', 1, 1, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Physiology 1 (for physiotherapy)'),
   'BMS136', 1, 1, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Biochemistry (for physiotherapy)'),
   'BMS149', 1, 1, 4, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'University Requirement (1)'),
   'UC1', 1, 1, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Kinesiology 1'),
   'BPT112', 1, 2, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Tests and Measurements 1'),
   'BPT113', 1, 2, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Anatomy 2 (for physiotherapy)'),
   'BMS116', 1, 2, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Histology 2 (for physiotherapy)'),
   'BMS125', 1, 2, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Physiology 2 (for physiotherapy)'),
   'BMS137', 1, 2, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'University Requirement (2)'),
   'UC2', 1, 2, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'University Requirement (3)'),
   'UC3', 1, 2, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Kinesiology 2'),
   'BPT214', 2, 3, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Tests and Measurements 2'),
   'BPT215', 2, 3, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Growth and Development and Human Genetics'),
   'PTH241', 2, 3, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Neuroanatomy (for physiotherapy)'),
   'BMS211', 2, 3, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Neurophysiology 1 (for physiotherapy)'),
   'BMS234', 2, 3, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Clinical Biochemistry (for physiotherapy)'),
   'BMS244', 2, 3, 4, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Biomechanics 1'),
   'BPT216', 2, 4, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Therapeutic Modalities'),
   'BPT217', 2, 4, 6, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Exercise Physiology'),
   'BPT218', 2, 4, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Anatomy 3 (for physiotherapy)'),
   'BMS212', 2, 4, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Neurophysiology 2 (for physiotherapy)'),
   'BMS235', 2, 4, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'University Requirement (4)'),
   'UC4', 2, 4, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Biomechanics 2'),
   'BPT319', 3, 5, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Pathology 1 (for physiotherapy)'),
   'BMS352', 3, 5, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Pharmacology 1 (for physiotherapy)'),
   'BMS361', 3, 5, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Theory of Internal Medicine (for physiotherapy)'),
   'CMS313', 3, 5, 8, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Cardiothoracic Surgery (for physiotherapy)'),
   'CMS321', 3, 5, 1, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Radiology 1 (for physiotherapy)'),
   'CMS322', 3, 5, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Elective Course (1)'),
   'E1', 3, 5, 3, false),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Cardiopulmonary and Internal Medicine PT and Rehabilitation'),
   'PTM322', 3, 6, 8, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Pathology 2 (for physiotherapy)'),
   'BMS353', 3, 6, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Pharmacology 2 (for physiotherapy)'),
   'BMS362', 3, 6, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'General Surgery (for physiotherapy)'),
   'CMS323', 3, 6, 3, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Obstetrics & Gynaecology (for physiotherapy)'),
   'CMS342', 3, 6, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Public Health (for physiotherapy)'),
   'CMS383', 3, 6, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Elective Course (2)'),
   'E2', 3, 6, 2, false),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Integumentary PT and Rehabilitation'),
   'PTM423', 4, 7, 5, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Woman Health PT and Rehabilitation'),
   'PTH442', 4, 7, 4, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Radiology 2 (for physiotherapy)'),
   'CMS423', 4, 7, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Traumatology and Orthopaedic Surgery'),
   'CMS424', 4, 7, 4, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'University Requirement (5)'),
   'UC5', 4, 7, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'University Requirement (6)'),
   'UC6', 4, 7, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Elective University Requirement (1)'),
   'UE1', 4, 7, 2, false),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Sport injuries PT and Rehabilitation'),
   'PTO431', 4, 8, 7, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Orthopaedics PT and Rehabilitation'),
   'PTO432', 4, 8, 7, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Paediatric Surgery (for physiotherapy)'),
   'CMS426', 4, 8, 1, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Paediatrics (for physiotherapy)'),
   'CMS433', 4, 8, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Elective Course (3)'),
   'E3', 4, 8, 2, false),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Orthoses and Prostheses'),
   'PTO433', 4, 8, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Paediatrics PT and Rehabilitation'),
   'PTH543', 5, 9, 8, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Electro-diagnosis (for physiotherapy)'),
   'BMS431', 5, 9, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Neuropsychiatry (for physiotherapy)'),
   'CMS512', 5, 9, 4, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Neurosurgery (for physiotherapy)'),
   'CMS522', 5, 9, 1, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Radiology 3 (for physiotherapy)'),
   'CMS523', 5, 9, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Elective Course (4)'),
   'E4', 5, 9, 1, false),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'University Requirement (7)'),
   'UC7', 5, 9, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Elective University (2)'),
   'UE2', 5, 9, 2, false),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Neurology PT and Rehabilitation'),
   'PTN552', 5, 10, 7, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Neurosurgery PT and Rehabilitation'),
   'PTN553', 5, 10, 4, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Differential Diagnosis 1 (for physiotherapy)'),
   'CMS502', 5, 10, 2, true),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Elective Course (5)'),
   'E5', 5, 10, 2, false),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Elective University (3)'),
   'UE3', 5, 10, 2, false),
  ((select id from programs where name = 'Physical Therapy Program'),
   (select id from courses where name = 'Graduation Research Project'),
   'BPT514', 5, 10, 2, true);

-- Step 5: insert prerequisite links
insert into course_prerequisites (course_id, prerequisite_course_id)
values
  ((select id from program_courses where code = 'BPT112'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BPT113'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BMS116'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BMS125'),
   (select id from program_courses where code = 'BMS124')),
  ((select id from program_courses where code = 'BMS137'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'BPT214'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BPT214'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'BPT214'),
   (select id from program_courses where code = 'BPT112')),
  ((select id from program_courses where code = 'BPT215'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'BPT215'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BPT215'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'BMS244'),
   (select id from program_courses where code = 'BMS149')),
  ((select id from program_courses where code = 'BPT216'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BPT216'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'BPT216'),
   (select id from program_courses where code = 'BPT112')),
  ((select id from program_courses where code = 'BPT216'),
   (select id from program_courses where code = 'BPT214')),
  ((select id from program_courses where code = 'BPT217'),
   (select id from program_courses where code = 'PHY112')),
  ((select id from program_courses where code = 'BPT217'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BPT217'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'BPT217'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'BPT217'),
   (select id from program_courses where code = 'BPT215')),
  ((select id from program_courses where code = 'BPT218'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'BPT218'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'BMS212'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BMS212'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'BMS235'),
   (select id from program_courses where code = 'BMS234')),
  ((select id from program_courses where code = 'BPT319'),
   (select id from program_courses where code = 'BPT216')),
  ((select id from program_courses where code = 'BPT319'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BPT319'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'BPT319'),
   (select id from program_courses where code = 'BPT112')),
  ((select id from program_courses where code = 'BPT319'),
   (select id from program_courses where code = 'BPT214')),
  ((select id from program_courses where code = 'BMS352'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'BMS352'),
   (select id from program_courses where code = 'BMS124')),
  ((select id from program_courses where code = 'BMS352'),
   (select id from program_courses where code = 'BMS125')),
  ((select id from program_courses where code = 'BMS352'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'BMS352'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'BMS361'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'BMS361'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'BMS361'),
   (select id from program_courses where code = 'BMS234')),
  ((select id from program_courses where code = 'BMS361'),
   (select id from program_courses where code = 'BMS235')),
  ((select id from program_courses where code = 'CMS313'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'CMS313'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'CMS313'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS313'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS313'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'CMS321'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS321'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS321'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'CMS321'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'CMS321'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'CMS322'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS322'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS322'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'CMS322')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'CMS321')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BPT217')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'PHY112')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BPT215')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BPT218')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BMS124')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'BMS125')),
  ((select id from program_courses where code = 'PTM322'),
   (select id from program_courses where code = 'CMS313')),
  ((select id from program_courses where code = 'BMS353'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'BMS353'),
   (select id from program_courses where code = 'BMS124')),
  ((select id from program_courses where code = 'BMS353'),
   (select id from program_courses where code = 'BMS125')),
  ((select id from program_courses where code = 'BMS353'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'BMS353'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'BMS353'),
   (select id from program_courses where code = 'BMS352')),
  ((select id from program_courses where code = 'BMS362'),
   (select id from program_courses where code = 'BMS361')),
  ((select id from program_courses where code = 'CMS323'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'CMS323'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'CMS323'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS323'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS323'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'CMS323'),
   (select id from program_courses where code = 'BMS124')),
  ((select id from program_courses where code = 'CMS323'),
   (select id from program_courses where code = 'BMS125')),
  ((select id from program_courses where code = 'CMS342'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'CMS342'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'CMS342'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS342'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS342'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'PTM423'),
   (select id from program_courses where code = 'CMS313')),
  ((select id from program_courses where code = 'PTM423'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'PTM423'),
   (select id from program_courses where code = 'BMS124')),
  ((select id from program_courses where code = 'PTM423'),
   (select id from program_courses where code = 'BMS125')),
  ((select id from program_courses where code = 'PTM423'),
   (select id from program_courses where code = 'BPT217')),
  ((select id from program_courses where code = 'PTM423'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'PTM423'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'PTM423'),
   (select id from program_courses where code = 'CMS323')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'CMS342')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'BPT217')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'PHY112')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'PTH442'),
   (select id from program_courses where code = 'BPT215')),
  ((select id from program_courses where code = 'CMS423'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS423'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS423'),
   (select id from program_courses where code = 'CMS322')),
  ((select id from program_courses where code = 'CMS424'),
   (select id from program_courses where code = 'BPT216')),
  ((select id from program_courses where code = 'CMS424'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS424'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS424'),
   (select id from program_courses where code = 'BPT112')),
  ((select id from program_courses where code = 'CMS424'),
   (select id from program_courses where code = 'BPT214')),
  ((select id from program_courses where code = 'CMS424'),
   (select id from program_courses where code = 'BPT319')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'BPT217')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'PHY112')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'BPT215')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'CMS424')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'CMS423')),
  ((select id from program_courses where code = 'PTO431'),
   (select id from program_courses where code = 'CMS322')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'BPT217')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'PHY112')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'BPT215')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'CMS424')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'CMS322')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'CMS423')),
  ((select id from program_courses where code = 'PTO432'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'CMS426'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS426'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS426'),
   (select id from program_courses where code = 'BMS211')),
  ((select id from program_courses where code = 'CMS426'),
   (select id from program_courses where code = 'PTH241')),
  ((select id from program_courses where code = 'CMS433'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'CMS433'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS433'),
   (select id from program_courses where code = 'BMS211')),
  ((select id from program_courses where code = 'CMS433'),
   (select id from program_courses where code = 'PTH241')),
  ((select id from program_courses where code = 'PTO433'),
   (select id from program_courses where code = 'CMS424')),
  ((select id from program_courses where code = 'PTO433'),
   (select id from program_courses where code = 'CMS423')),
  ((select id from program_courses where code = 'PTO433'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'PTO433'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'PTO433'),
   (select id from program_courses where code = 'BMS212')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'PTH241')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'BPT217')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'PHY112')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'BPT215')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'CMS433')),
  ((select id from program_courses where code = 'PTH543'),
   (select id from program_courses where code = 'CMS426')),
  ((select id from program_courses where code = 'BMS431'),
   (select id from program_courses where code = 'BMS234')),
  ((select id from program_courses where code = 'BMS431'),
   (select id from program_courses where code = 'BMS235')),
  ((select id from program_courses where code = 'BMS431'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'BMS431'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'CMS512'),
   (select id from program_courses where code = 'BMS211')),
  ((select id from program_courses where code = 'CMS512'),
   (select id from program_courses where code = 'BMS234')),
  ((select id from program_courses where code = 'CMS512'),
   (select id from program_courses where code = 'BMS235')),
  ((select id from program_courses where code = 'CMS512'),
   (select id from program_courses where code = 'BMS361')),
  ((select id from program_courses where code = 'CMS512'),
   (select id from program_courses where code = 'BMS362')),
  ((select id from program_courses where code = 'CMS522'),
   (select id from program_courses where code = 'BMS211')),
  ((select id from program_courses where code = 'CMS522'),
   (select id from program_courses where code = 'BMS234')),
  ((select id from program_courses where code = 'CMS522'),
   (select id from program_courses where code = 'BMS235')),
  ((select id from program_courses where code = 'CMS523'),
   (select id from program_courses where code = 'BMS211')),
  ((select id from program_courses where code = 'CMS523'),
   (select id from program_courses where code = 'BMS234')),
  ((select id from program_courses where code = 'CMS523'),
   (select id from program_courses where code = 'BMS235')),
  ((select id from program_courses where code = 'CMS523'),
   (select id from program_courses where code = 'CMS423')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BPT217')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'PHY112')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BPT215')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BPT218')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS136')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS137')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS211')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS234')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS235')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS361')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'BMS362')),
  ((select id from program_courses where code = 'PTN552'),
   (select id from program_courses where code = 'CMS512')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'BMS211')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'BMS234')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'BMS235')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'CMS522')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'BPT217')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'PHY112')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'BMS115')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'BMS116')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'BPT113')),
  ((select id from program_courses where code = 'PTN553'),
   (select id from program_courses where code = 'BPT215')),
  ((select id from program_courses where code = 'CMS502'),
   (select id from program_courses where code = 'CMS424')),
  ((select id from program_courses where code = 'CMS502'),
   (select id from program_courses where code = 'CMS512')),
  ((select id from program_courses where code = 'CMS502'),
   (select id from program_courses where code = 'CMS522')),
  ((select id from program_courses where code = 'CMS502'),
   (select id from program_courses where code = 'CMS313')),
  ((select id from program_courses where code = 'CMS502'),
   (select id from program_courses where code = 'CMS323'));

-- Missing prerequisite in source data:
-- LIB116 is referenced by BPT514 but is not present in data.js