import { getApiCandidates, saveApiBase } from './shared/apiConfig.js';
import { portalPath, restoreSession, signOut } from './shared/session.js';

const avatars = ['👨🏻‍🎓','👨🏽‍💼','👨🏿‍🏫','👩🏻‍🎓','👩🏽‍💼','👩🏿‍🏫'];
const labels = { student: 'Student', regular_admin: 'Academic Administrator', super_admin: 'Super Admin' };
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const date = value => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not available';
let user = await restoreSession();
if (!user) location.replace('./index.html');

async function api(path, options = {}) {
  let lastError;
  for (const base of getApiCandidates()) try { const response = await fetch(`${base}${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error || 'Request failed.'); saveApiBase(base); return data; } catch (error) { lastError = error; }
  throw lastError;
}
function avatar(profile) { return profile.avatarData ? `<img class="avatar custom-image" src="${profile.avatarData}" alt="Custom avatar for ${escapeHtml(profile.name)}">` : `<span class="avatar" aria-label="Selected avatar">${avatars[Number((profile.avatarKey || 'avatar-1').split('-')[1]) - 1] || avatars[0]}</span>`; }
function actions(role) {
  const student = [['Continue Study Plan', portalPath('student')], ['Search Course', `${portalPath('student')}#catalog`], ['Open Program', `${portalPath('student')}#catalog`], ['View Notifications', '#notifications'], ['View Profile', '#profile'], ['Change Password', './password-reset-request.html']];
  const admin = [['Course Manager', portalPath('admin')], ['Add Course', `${portalPath('admin')}#courses`], ['Manage Relations', `${portalPath('admin')}#relations`], ['Import', `${portalPath('admin')}#import`], ['Program Management', `${portalPath('admin')}#programs`], ['Faculty Management', `${portalPath('admin')}#faculties`]];
  const superAdmin = [['User Management', `${portalPath('admin')}#users`], ['Requests & Complaints', `${portalPath('admin')}#requests`], ['Audit Logs', `${portalPath('admin')}#audit`], ['Backup', `${portalPath('admin')}#backup`], ['Export', `${portalPath('admin')}#export`], ['Recycle Bin', `${portalPath('admin')}#recycle-bin`], ['System Health', `${portalPath('admin')}#system-health`], ['Student Portal', portalPath('student')], ['Admin Portal', portalPath('admin')]];
  return role === 'student' ? student : role === 'regular_admin' ? admin : superAdmin;
}
function card(title, body, extra = '') { return `<section class="dash-card ${extra}"><h2>${title}</h2>${body}</section>`; }
function metrics(counts = {}) { return `<div class="metric-grid">${[['Faculties', counts.faculties],['Programs', counts.programs],['Courses', counts.courses],['Program courses', counts.programCourses],['Relationships', counts.relationships],['Hidden relations', counts.hiddenRelationships]].map(([k,v]) => `<div><strong>${v ?? 0}</strong><span>${k}</span></div>`).join('')}</div>`; }
function render(data) {
  user = data.profile; const welcome = user.role === 'student' ? `Welcome back, ${escapeHtml(user.name)}.` : user.role === 'regular_admin' ? `Welcome back, ${escapeHtml(user.name)}. Here's today's academic administration overview.` : `Welcome back, ${escapeHtml(user.name)}. Here's your system overview.`;
  document.getElementById('identity-header').innerHTML = `${avatar(user)}<div><p class="role-label">${labels[user.role]}</p><h1>${escapeHtml(user.name)}</h1><p>@${escapeHtml(user.username || 'username')} · <span class="status">${escapeHtml(user.status)}</span></p>${user.studentId ? `<p>Student ID: ${escapeHtml(user.studentId)}</p>` : ''}</div><button id="edit-profile" class="button secondary">Profile</button>`;
  const unread = data.notifications.filter(n => !n.read).length; document.getElementById('notification-count').hidden = !unread; document.getElementById('notification-count').textContent = unread;
  const noticeList = data.notifications.length ? `<ul class="activity-list">${data.notifications.map(n => `<li><strong>${escapeHtml(n.title)}</strong><span>${escapeHtml(n.description)}</span><time>${date(n.timestamp)}</time></li>`).join('')}</ul>` : '<p class="empty">No stored notifications yet.</p>';
  const recent = data.recentActivity.length ? `<ul class="activity-list">${data.recentActivity.map(a => `<li><strong>${escapeHtml(a.action)}</strong><span>${escapeHtml(a.description || '')}</span><time>${date(a.created_at)}</time></li>`).join('')}</ul>` : '<p class="empty">No recorded activity yet.</p>';
  const quick = `<div class="quick-grid">${actions(user.role).map(([label, href]) => `<a href="${href}" class="quick-action">${label}<span aria-hidden="true">→</span></a>`).join('')}</div>`;
  const security = `<dl class="security-list"><div><dt>Email</dt><dd>${escapeHtml(user.email)}</dd></div><div><dt>Username</dt><dd>@${escapeHtml(user.username || '')}</dd></div><div><dt>Account status</dt><dd>${escapeHtml(user.status)}</dd></div><div><dt>Last login</dt><dd>${date(user.lastLogin)}</dd></div><div><dt>Password last changed</dt><dd>${date(user.passwordChangedAt)}</dd></div></dl><div class="inline-actions"><a class="button secondary" href="./password-reset-request.html">Change Password</a><button id="security-sign-out" class="button danger">Sign Out</button></div>`;
  const progress = data.studyProgress ? card('Study Progress', `<p class="future-note">${escapeHtml(data.studyProgress.message)}</p><p class="muted">Prepared for academic level, semester, completed courses, earned credits, grades, prerequisite alerts, and progress when the university records integration is available.</p>`) : '';
  const system = user.role === 'super_admin' ? card('System Health', `<p><strong>${escapeHtml(data.systemHealth?.backendStatus || 'Unknown')}</strong> backend · <strong>${escapeHtml(data.systemHealth?.databaseStatus || 'Unknown')}</strong> database</p>${data.userCounts ? `<p class="muted">${data.userCounts.users} users · ${data.userCounts.active_users} active · ${data.userCounts.suspended_users} suspended</p>` : ''}`) : '';
  const overview = user.role === 'student' ? '' : card(user.role === 'super_admin' ? 'Full System Overview' : 'Academic Catalog Overview', metrics(data.catalog?.counts));
  document.getElementById('dashboard-content').innerHTML = `<section class="welcome"><p class="role-label">Dashboard</p><h2>${welcome}</h2></section>${overview}${card('Quick Access', quick)}${progress}${card('Notifications', `<div id="notifications">${noticeList}</div>`)}${card('Recent Activity', recent)}${system}${card('Account & Security', security)}`;
  document.getElementById('edit-profile').addEventListener('click', openProfile); document.getElementById('security-sign-out').addEventListener('click', logout); document.getElementById('notification-button').addEventListener('click', () => document.getElementById('notifications').scrollIntoView({ behavior: 'smooth' }));
}
function openProfile() { const form = document.getElementById('profile-form'); form.name.value = user.name; form.username.value = user.username || ''; document.getElementById('avatar-options').innerHTML = avatars.map((icon, i) => `<label class="avatar-choice"><input type="radio" name="avatarKey" value="avatar-${i+1}" ${user.avatarKey === `avatar-${i+1}` ? 'checked' : ''}><span>${icon}</span><b>${i < 3 ? 'Masc.' : 'Fem.'} ${i % 3 + 1}</b></label>`).join(''); document.getElementById('profile-error').textContent = ''; document.getElementById('profile-dialog').showModal(); }
document.getElementById('profile-form').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; try { const payload = { name: form.name.value, username: form.username.value, avatarKey: new FormData(form).get('avatarKey') }; const file = document.getElementById('avatar-upload').files[0]; if (file) { if (file.size > 700 * 1024) throw new Error('Custom avatar must be smaller than 700 KB.'); payload.avatarData = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); } const response = await api('/profile', { method: 'PUT', body: JSON.stringify(payload) }); user = response.user; document.getElementById('profile-dialog').close(); render(await api('/dashboard')); } catch (error) { document.getElementById('profile-error').textContent = error.message; } });
document.getElementById('close-profile').addEventListener('click', () => document.getElementById('profile-dialog').close()); document.getElementById('cancel-profile').addEventListener('click', () => document.getElementById('profile-dialog').close());
document.getElementById('remove-avatar').addEventListener('click', async () => { try { await api('/profile', { method: 'PUT', body: JSON.stringify({ avatarData: '' }) }); document.getElementById('profile-dialog').close(); render(await api('/dashboard')); } catch (error) { document.getElementById('profile-error').textContent = error.message; } });
async function logout() { await signOut('./index.html'); }
document.getElementById('sign-out').addEventListener('click', logout);
try { render(await api('/dashboard')); } catch (error) { document.getElementById('dashboard-content').innerHTML = `<p class="error">${escapeHtml(error.message)}</p>`; }
