export async function listUserNotifications(userId, executor) { return (await executor.query('SELECT id,subject AS title,body AS description,created_at AS timestamp,kind AS category FROM public.communication_outbox WHERE recipient_id=$1 ORDER BY created_at DESC LIMIT 8', [userId])).rows; }

export async function listStudentActivity(userId, executor) { return (await executor.query('SELECT id,created_at,subject AS action,body AS description FROM public.communication_outbox WHERE recipient_id=$1 ORDER BY created_at DESC LIMIT 6', [userId])).rows; }
export async function listAdminActivity(executor) { return (await executor.query('SELECT id,created_at,action,description FROM admin_audit_logs ORDER BY created_at DESC LIMIT 6')).rows; }
export async function listOpenResetNotifications(executor) { return (await executor.query("SELECT id,created_at FROM public.password_reset_requests WHERE status='open' ORDER BY created_at DESC LIMIT 8")).rows; }
export async function listOpenComplaintNotifications(executor) { return (await executor.query("SELECT id,created_at FROM public.student_complaints WHERE status <> 'resolved' ORDER BY created_at DESC LIMIT 8")).rows; }
export async function listRecentBackupNotifications(executor) { return (await executor.query('SELECT id,created_at FROM admin_backup_history ORDER BY created_at DESC LIMIT 8')).rows; }
export async function userStatusCounts(executor) { return (await executor.query("SELECT count(*)::int AS users,count(*) FILTER (WHERE status='active')::int AS active_users,count(*) FILTER (WHERE status='suspended')::int AS suspended_users FROM public.app_users")).rows[0] || null; }
export async function createComplaintRecord(user, message, executor) { return (await executor.query('INSERT INTO public.student_complaints (student_id,email,message) VALUES ($1,$2,$3) RETURNING *', [user.student_id, user.email, message])).rows[0] || null; }
export async function listComplaintRecords(executor) { return (await executor.query('SELECT * FROM public.student_complaints ORDER BY created_at DESC')).rows; }
export async function updateComplaintRecord(id, status, reply, actorId, executor) { return (await executor.query('UPDATE public.student_complaints SET status=$2,reply=$3,handled_by=$4,updated_at=now() WHERE id=$1 RETURNING *', [id, status, String(reply || '').slice(0, 4000), actorId])).rows[0] || null; }
export async function createCommunicationRecord(recipientId, message, senderId, executor) { return (await executor.query("INSERT INTO public.communication_outbox (recipient_id,sender_id,kind,subject,body,status) VALUES ($1,$2,'message','Message from Galala University',$3,'queued') RETURNING *", [recipientId, senderId, message])).rows[0] || null; }
export async function listCommunicationRecords(executor) { return (await executor.query(`SELECT c.id,c.kind,c.subject,c.body,c.status,c.created_at,u.name AS recipient_name,u.email AS recipient_email FROM public.communication_outbox c JOIN public.app_users u ON u.id=c.recipient_id ORDER BY c.created_at DESC`)).rows; }
